//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGP.Modules.ServerControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LGP.Modules.ServerControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client updates.
        /// </summary>
        internal static string ClientUpdates {
            get {
                return ResourceManager.GetString("ClientUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms delay.
        /// </summary>
        internal static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected Servers.
        /// </summary>
        internal static string Detected {
            get {
                return ResourceManager.GetString("Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Server Connection.
        /// </summary>
        internal static string ManualConnection {
            get {
                return ResourceManager.GetString("ManualConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Control.
        /// </summary>
        internal static string PolicyControl {
            get {
                return ResourceManager.GetString("PolicyControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests sent.
        /// </summary>
        internal static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server connection required.
        /// </summary>
        internal static string ServerConnectionRequired {
            get {
                return ResourceManager.GetString("ServerConnectionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server control.
        /// </summary>
        internal static string ServerControl {
            get {
                return ResourceManager.GetString("ServerControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Discovery.
        /// </summary>
        internal static string ServerDiscovery {
            get {
                return ResourceManager.GetString("ServerDiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Identification.
        /// </summary>
        internal static string ServerId {
            get {
                return ResourceManager.GetString("ServerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Ip address.
        /// </summary>
        internal static string ServerIp {
            get {
                return ResourceManager.GetString("ServerIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulate.
        /// </summary>
        internal static string Simulate {
            get {
                return ResourceManager.GetString("Simulate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stress Test.
        /// </summary>
        internal static string StressTest {
            get {
                return ResourceManager.GetString("StressTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize Clients.
        /// </summary>
        internal static string SyncClients {
            get {
                return ResourceManager.GetString("SyncClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize Modules.
        /// </summary>
        internal static string SyncModules {
            get {
                return ResourceManager.GetString("SyncModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize Policies.
        /// </summary>
        internal static string SyncPolicies {
            get {
                return ResourceManager.GetString("SyncPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working.
        /// </summary>
        internal static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
    }
}
